TimeSheets.Web/Controllers/ShiftController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TimeSheets.Core.Model;
using TimeSheets.Core.Services;
using TimeSheets.Web.ViewModels.ShiftVM;

namespace TimeSheets.Web.Controllers
{
    public class ShiftController : BaseController
    {
        private ShiftService _shiftService;
        private StaffService _staffService;
        private BranchService _branchService;

        public ShiftController(ShiftService shiftService, StaffService staffService, BranchService branchService)
        {
            _branchService = branchService;
            _shiftService = shiftService;
            _staffService = staffService;
        }

        //
        // GET: /Shift/
        [HttpGet]
        [ActionName("Index")]
        public ActionResult Index_Get(DateTime? id)
        {
            //todo list of shift for today
            var dateToGetShiftsFor = new DateTime();
            if (id == null)
            {
                dateToGetShiftsFor = DateTime.Today;
            }
            else
            {
                dateToGetShiftsFor = (DateTime) id;
            }
            IEnumerable<Shift> todayShifts = _shiftService.GetShifts(1, dateToGetShiftsFor);
            var viewModel = new ShiftIndexViewModel();
            viewModel.ShiftList = todayShifts;
            viewModel.DateBeingViewed = dateToGetShiftsFor;
            viewModel.BranchSelectList = new SelectList(_branchService.GetAllBranches(),"Id","Name");
            return View(viewModel);
        }
        
        [HttpPost]
        [ActionName("Index")]
        public ActionResult Index_Post(DateTime dateBeingViewed, int branchId)
        {
            //todo list of shift for today
            IEnumerable<Shift> todayShifts = _shiftService.GetShifts(branchId, dateBeingViewed);
            var viewModel = new ShiftIndexViewModel();
            viewModel.ShiftList = todayShifts;
            viewModel.DateBeingViewed = dateBeingViewed;
            viewModel.BranchSelectList = new SelectList(_branchService.GetAllBranches(),"Id","Name");
            return View(viewModel);
        }
        public ActionResult Date(DateTime dateTime)
        {
            //todo display shifts for specific day
            return View();
        }


        [HttpGet]
        [ActionName("Create")]
        public ActionResult Create_Get()
        {
            ShiftCreateViewModel viewModel = new ShiftCreateViewModel();
            return View(viewModel);
        }

        [HttpPost]
        [ActionName("Create")]
        public ActionResult Create_Post(Shift shift)
        {
            shift.BranchId = 1;
            if (ModelState.IsValid)
            {
                _shiftService.CreateShift(shift);
                return RedirectToAction("Index");
                
            }
            else
            {
                var viewModel = new ShiftCreateViewModel {Shift = shift};
                return View(viewModel);
            }
        }

        [HttpGet]
        public ActionResult AddRemoveStaff(int id)
        {
            var viewModel = new ShiftAddRemoveViewModel();
            Shift shift = _shiftService.GetShiftForAddRemoveStaff(id);
            viewModel.Shift = shift;
            viewModel.StaffAvailableForShift = _staffService.GetStaffAvailableToWorkThisShift(shift);
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult AddRemoveStaff(ICollection<int> staffIdsToAdd, ICollection<int> staffIdsToRemove, int shiftId)
        {
            _shiftService.AddStaffWithGivenIdsToShift(staffIdsToAdd, shiftId);
            _shiftService.RemoveStaffWithGivenIdsFromShift(staffIdsToRemove, shiftId);

            return RedirectToAction("Index");
        }



    }
}

TimeSheets.Web/Views/Shift/AddRemoveStaff.cshtml
@using System.Activities.Statements
@using System.Runtime.Remoting.Messaging
@using TimeSheets.Core.Model
@model TimeSheets.Web.ViewModels.ShiftVM.ShiftAddRemoveViewModel

@{
    ViewBag.Title = "AddRemoveStaff";
}
<div class="container">
    @using (Html.BeginForm())
    {
        

        <h2>Add / Remove Staff - Shift @Model.Shift.StartDateTime.ToString("HH:mm") to @Model.Shift.FinishDateTime.ToString("HH:mm")</h2>

        <table class="table table-striped table-hover table-bordered">
            <tr>
                <th class="tab">Name
                </th>
                <th>Working
                </th>
            </tr>
            @if (Model.StaffAvailableForShift != null && Model.StaffAvailableForShift.Count() != 0)
            {
                foreach (var staff in Model.StaffAvailableForShift)
                {
                <tr>
                    <td>
                        @staff.Name
                    </td>
                    <td>
                        @{
                    var IsInShift = Model.Shift.StaffShifts.Any(x => x.StaffId == staff.Id);
                        }
                        @if (IsInShift)
                        {
                            <input name="staffInShift" type="checkbox" checked="true" value="@staff.Id.ToString()"/>
                            <input name="staffIdsToRemove"type="hidden" value="@staff.Id.ToString()"  disabled="true"/>
                            <input name="staffIdsToAdd"type="hidden" value="@staff.Id.ToString()"  disabled="true"/>
                        }
                        else
                        {
                            <input name="staffNotInShift" type="checkbox" value="@staff.Id.ToString()"/>
                            <input name="staffIdsToRemove"type="hidden" value="@staff.Id.ToString()" disabled="true"/>
                            <input name="staffIdsToAdd"type="hidden" value="@staff.Id.ToString()"  disabled="true"/>
                        }
                    </td>
                </tr>
                }
            }
            else
            {
                <tr>
                    <td colspan="2"><span class="text-muted">No staff availabe to work shift</span></td>
                </tr>
            }
        </table>
        <input type="hidden" name="shiftId" value="@Model.Shift.Id"/>
        <div>
            <input type="submit" value="Save" class="btn btn-success" />
            @Html.ActionLink("Cancel", "Index", "Shift", null, new { @class = "btn btn-danger" })
        </div>
        
    }
    @section Scripts
    {
        <script>
            var testnum = 1;
            $("input[type='checkbox']").change(function ()
            {
                var staffId = this.value;
                if (this.checked)
                {
                    if (this.name == "staffNotInShift")
                    {
                        $("input[type='hidden'][name='staffIdsToAdd'][value='" + staffId + "']").prop("disabled", false);
                    }
                    else if (this.name == "staffInShift")
                    {
                        $("input[type='hidden'][name='staffIdsToAdd'][value='" + staffId + "']").prop('disabled', true);
                        $("input[type='hidden'][name='staffIdsToRemove'][value='" + staffId + "']").prop('disabled', true);
                    }
                } else
                {
                    if (this.name == "staffNotInShift")
                    {
                        $("input[type='hidden'][name='staffIdsToRemove'][value='" + staffId + "']").prop('disabled', true);
                        $("input[type='hidden'][name='staffIdsToAdd'][value='" + staffId + "']").prop('disabled', true);
                    }
                    else if (this.name == "staffInShift")
                    {
                        $("input[type='hidden'][name='staffIdsToRemove'][value='" + staffId + "']").prop("disabled", false);

                    }
                }
            });
        </script>
    }
</div>

TimeSheets.Web/Views/Shift/Create.cshtml
<div class="container">
    @using TimeSheets.Web.CustomHtmlHelpers    @model TimeSheets.Web.ViewModels.ShiftVM.ShiftCreateViewModel

    @{
        ViewBag.Title = "Create";
    }
    <h2>Create</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        
        
        
        
        
        
        
        <fieldset>
            <legend>Shift</legend>

            <div class="editor-label">
                @Html.LabelFor(model => model.Shift.StartDateTime)

            </div>
            <div class="editor-field">
                <div class="row">
                    <div class='col-sm-6'>

                        <div class="form-group">
                            @* todo why does jquery expect one format, and mvc server expect another for dates? *@
                            @Html.DateTimeFor(model => model.Shift.StartDateTime)
                        </div>
                    </div>

                </div>
                @Html.ValidationMessageFor(model => model.Shift.StartDateTime)
            </div>


            <div class="editor-label">
                @Html.LabelFor(model => model.Shift.FinishDateTime)
            </div>
            <div class="editor-field">
                <div class="row">
                    <div class='col-sm-6'>
                        <div class="form-group">
                            @Html.DateTimeFor(model => model.Shift.FinishDateTime)
                        </div>
                    </div>
                    <script type="text/javascript">
                        
                    </script>
                </div>
                @Html.ValidationMessageFor(model => model.Shift.FinishDateTime)







            </div>


            <div>
                <input type="submit" value="Create" class="btn btn-success" />
                @Html.ActionLink("Cancel", "Index", "Shift", null, new { @class = "btn btn-danger" })
            </div>
        </fieldset>
    }


</div>

@section Scripts{

}

TimeSheets.Web/Views/Shift/Index.cshtml
@using TimeSheets.Core.Model
@using TimeSheets.Web.CustomHtmlHelpers
@model TimeSheets.Web.ViewModels.ShiftVM.ShiftIndexViewModel

@{
    ViewBag.Title = "Index";
}
<div class="container">

    <div class="col-md-1 col-sm-4">
        <h2 id="shiftheader">Shifts</h2>
    </div>
    <div class="col-md-7 col-md-offset-1 col-sm-8">
        @using (Html.BeginForm("Index", "Shift", FormMethod.Post, new { id = "shiftDateSelectorForm" }))
        {
            <div class="col-md-5 col-sm-5 col-xs-12">
                @Html.DateFor(m => m.DateBeingViewed) 
            </div>
            <div class="col-md-5 col-sm-5 col-xs-12">
                @Html.DropDownList("branchId",Model.BranchSelectList, new{@class="form-control"})
                @*@Html.DropDownList("Branches",new List<SelectListItem>
                {
                    new SelectListItem {Text = "Verulam", Value = "1",Selected = true},
                    new SelectListItem {Text = "Telebetting", Value = "2"}
                }, new{@class="form-control"})*@
            </div>
            <div class="col-md-2 col-sm-2 col-xs-12">
                <input type="submit" value="Go" class="btn btn-success  col-md-10 col-md-offset-1 col-xs-12" />
            </div>
        }
    </div>



</div>
<div class="container">


    @foreach (var shift in Model.ShiftList)
    {
        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="">
                    <h5 class="col-md-6 col-xs-6">@shift.StartDateTime.ToString("HH:mm") - @shift.FinishDateTime.ToString("HH:mm")</h5>
                    <a href="@Url.Action("AddRemoveStaff", "Shift", new { id = shift.Id })" class ="btn btn-info btn-sm"  data-toggle="tooltip" data-placement="left" title="Add or Remove staff from this shift">Staff</a>
                </div>
            </div>
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-condensed table-hover">
                        <tr>
                            <th>Name</th>
                            <th>Time In</th>
                            <th>Time Out</th>
                            <th>Lunch Break</th>
                            <th></th>
                        </tr>
                        @if (shift.StaffShifts.Count() != 0)
                        {
                            foreach (var staffShift in shift.StaffShifts)
                            {
                            <tr id="@("staffShift" + staffShift.Id)">
                                @{Html.RenderPartial("_StaffShiftRow", staffShift);}
                            </tr>
                            }
                        }
                        else
                        {
                            <tr>
                                <td class="col-md-4"><span class="text-muted">No staff in shift</span></td>
                                <td class="col-md-2"></td>
                                <td class="col-md-2"></td>
                                <td class="col-md-3"></td>
                                <td class="col-md-1"></td>
                            </tr>
                        }
                    </table>
                </div>
            </div>
        </div>
    }


    <p>
        @Html.ActionLink("New Shift", "Create", "Shift", null, new { @class = "btn btn-info"  , data_toggle="tooltip" ,data_placement="left" ,title="Create another shift"})
    </p>
</div>