TimeSheets.Web/Controllers/StaffShiftController.cs
using System.Web.Mvc;
using TimeSheets.Core.Model;
using TimeSheets.Core.Services;
using TimeSheets.Web.ViewModels.StaffShiftVM;

namespace TimeSheets.Web.Controllers
{
    public class StaffShiftController : BaseController
    {
        private readonly StaffShiftService _staffShiftService;

        public StaffShiftController(StaffShiftService staffShiftService)
        {
            _staffShiftService = staffShiftService;
        }

        public ActionResult Index()
        {
            return View();
        }



        [HttpPost]
        [ActionName("Edit")]
        public ActionResult Edit_Post(TimesOverride timesOverride)
        {
            //todo neaten timesoverride post

            if (ModelState.IsValid)
            {
                StaffShift staffShift = _staffShiftService.GetStaffShiftById(timesOverride.StaffShiftId);
                if (timesOverride.OPaidStartTime.Value.AddHours(1) >= timesOverride.OPaidFinishTime.Value)
                {
                    ModelState.AddModelError(string.Empty, "Shift has to be longer than an hour");
                    var viewModel = new StaffShiftEditViewModel();
                    
                    viewModel.StaffShift = staffShift;
                    return View(viewModel);
                }
                if ((timesOverride.OPaidStartTime < staffShift.Shift.StartDateTime) || (timesOverride.OPaidFinishTime > staffShift.Shift.FinishDateTime))
                {
                    ModelState.AddModelError(string.Empty, "Times have to be within shift");
                    var viewModel = new StaffShiftEditViewModel();

                    viewModel.StaffShift = staffShift;
                    return View(viewModel);
                }

                _staffShiftService.ApplyOverrideTimes(timesOverride.StaffShiftId, timesOverride.OPaidStartTime, timesOverride.OPaidFinishTime);
                return RedirectToAction("Index", "Shift");
            }
            else
            {
                var viewModel = new StaffShiftEditViewModel();
                StaffShift staffShift = _staffShiftService.GetStaffShiftById(timesOverride.StaffShiftId);
                viewModel.StaffShift = staffShift;
                return View(viewModel);  
            }
            
        }

        [HttpGet]
        [ActionName("Edit")]
        public ActionResult Edit_Get(int id)
        {
            var viewModel = new StaffShiftEditViewModel();
            var staffShift = _staffShiftService.GetStaffShiftById(id);
            var timesOverride = new TimesOverride();
            timesOverride.SetTimesToStaffShiftForDisplay(staffShift);
            viewModel.StaffShift = staffShift;
            viewModel.TimesOverride = timesOverride;
            
            return View(viewModel);
        }

        [HttpPost]
        public PartialViewResult Sick(int id)
        {
            Latency();
            StaffShift staffShift = _staffShiftService.MarkShiftWithIdSick(id);
            return PartialView("_StaffShiftRow", staffShift);
        }

        [HttpPost]
        public ActionResult NotSick(int id)
        {
            Latency();
            StaffShift staffShift = _staffShiftService.MarkShiftWithIdNotSick(id);
            return PartialView("_StaffShiftRow", staffShift);
        }

        [HttpPost]
        public ActionResult OnLeave(int id)
        {
            Latency();
            StaffShift staffShift = _staffShiftService.MarkShiftWithIdOnLeave(id);
            return PartialView("_StaffShiftRow", staffShift);
        }

        [HttpPost]
        public ActionResult NotOnLeave(int id)
        {
            Latency();
            StaffShift staffShift = _staffShiftService.MarkShiftWithIdNotOnLeave(id);
            return PartialView("_StaffShiftRow", staffShift);
        }
        

        

        private void Latency()
        {
            //todo fake latency remove this before going to production
            //System.Threading.Thread.Sleep(1000);
        }

        public ActionResult RemOTimes(TimesOverride timesOverride)
        {
            _staffShiftService.RemoveOverridingTimes(timesOverride.StaffShiftId);
            return RedirectToAction("Index", "Shift");
        }
    }
}

TimeSheets.Web/Views/StaffShift/Edit.cshtml
@using TimeSheets.Core.Model
@using TimeSheets.Web.CustomHtmlHelpers
@model TimeSheets.Web.ViewModels.StaffShiftVM.StaffShiftEditViewModel

@{
    ViewBag.Title = "Edit";
}

<div class="container">
    <div class="col-md-6">
        @using (Html.BeginForm("Edit", "StaffShift", FormMethod.Post, new { @class = "form-horizontal" }))
        {
            @Html.AntiForgeryToken()
    
            <fieldset>
                <legend>Manual Time Entry</legend>
                @Html.HiddenFor(m => m.TimesOverride.StaffShiftId)
                @Html.ValidationMessageFor(m => m.TimesOverride.StaffShiftId)

                <div class="form-group">
                    @Html.LabelFor(m => m.TimesOverride.OPaidStartTime)
                    @Html.DateTimeFor(m => m.TimesOverride.OPaidStartTime)
                    @Html.ValidationMessageFor(m => m.TimesOverride.OPaidStartTime)
                </div>

                <div class="form-group">
                    @Html.LabelFor(m => m.TimesOverride.OPaidFinishTime)
                    @Html.DateTimeFor(m => m.TimesOverride.OPaidFinishTime)
                    @Html.ValidationMessageFor(m => m.TimesOverride.OPaidFinishTime)
                </div>


                @Html.ValidationSummary(true)



                <p>
                    <input type="submit" value="Save" class="btn btn-success btn-sm" />
                    @Html.ActionLink("Back to List", "Index", "Shift", null, new { @class = "btn btn-info btn-sm" })

                </p>
            </fieldset>
        }
        @if (Model.StaffShift.UseOverrideTimes)
        {
            using (Html.BeginForm("RemOTimes", "StaffShift",FormMethod.Post ,new { @class = "form-horizontal" }))
            {
                @Html.HiddenFor(m => m.TimesOverride.StaffShiftId)
                //@Html.HiddenFor(m => m.TimesOverride.OPaidFinishTime)
                //@Html.HiddenFor(m => m.TimesOverride.OPaidFinishTime)
                
                <input type="submit" value="Clear and Use Scan Times" class="btn btn-danger btn-sm" />
            }
        }

    </div>
</div>
@section Scripts {

}